#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/1509bf75-93ba-4174-9b84-dee2d4f457ba/ # 
version: v1
title: Planets API

/planets:
  get:    
    responses:
      200:
        body:
          application/json:
            example: [ { "planet": "Mercury", "moons": 0, "diameter": 4879, "distanceFromSun": 57.9 }, { "planet": "Venus", "moons": 0, "diameter": 12104, "distanceFromSun": 108.2 }, { "planet": "Earth", "moons": 1, "diameter": 12756, "distanceFromSun": 149.6 }, { "planet": "Mars", "moons": 0, "diameter": 6792, "distanceFromSun": 227.9 }, { "planet": "Jupiter", "moons": 67, "diameter": 142984, "distanceFromSun": 778.6 }, { "planet": "Saturn", "moons": 62, "diameter": 120536, "distanceFromSun": 1433.5 }, { "planet": "Uranus", "moons": 27, "diameter": 51118, "distanceFromSun": 2872.5 }, { "planet": "Neptune", "moons": 14, "diameter": 49528, "distanceFromSun": 4495.1 }, { "planet": "Pluto(Dwarf-Planet)", "moons": 5, "diameter": 2370, "distanceFromSun": 5906.4 } ]
                        

  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              example: { "id": 3, "planet": "Earth", "moons": 1, "diameter": 12756, "distanceFromSun": 149.6 }